### ISSUE TITLE
怎么下载呢

### ISSUE THREAD

**Issue by huigeopencv** [roceys/Taobao#11]
怎么下载呢？

**Comment by zhzhch335** [comment]
安装autojs的app 然后把脚本复制进去运行 如果一点编程基础都没有的话建议等大佬打包出来吧 毕竟也容易碰到各种各样奇怪的问题

**Comment by roceys** [comment]
这里下载 https://github.com/github-h/Auto.js/releases/tag/V4.1.1.Alpha2
