### ISSUE TITLE
金币每次只加100，200，

### ISSUE THREAD

**Issue by Hannah-my** [roceys/Taobao#12]
在用这个脚本的时候，执行完一次任务之后，只加一两百金币😂😂，但是用手划屏幕的话，每次任务加30000金币。
估计是淘宝检测到使用脚本了😨😨😨

**Comment by roceys** [comment]
昨晚上淘宝加了检测脚本。。。

**Comment by iverson0816** [comment]
淘宝确实有检测脚本，一用auto.js就不行了

**Comment by JunShine** [comment]
有人试过用autojs生成的apk可以吗？

**Comment by yun-yun** [comment]
不让淘宝获取应用列表，使用随机数来不断向下滑动，能解决吗

**Comment by iverson0816** [comment]
哥们 刚打了个包试了一下 还是不行 只能拿100

**Comment by zhulingbiezhi** [comment]
求更新

**Comment by roceys** [comment]
> 有人试过用autojs生成的apk可以吗？

也不行，我打包测试过了，禁用了所有权限也不可以，大概率是通过无障碍来检测的。

**Comment by roceys** [comment]
暂时不自动任务的就单独使用撸猫脚本吧，过检测得root后屏蔽相关Service才能防止了。

**Comment by roceys** [comment]
> 不让淘宝获取应用列表，使用随机数来不断向下滑动，能解决吗

不行

**Comment by Eplayed** [comment]
有解决办法吗？

**Comment by zhulingbiezhi** [comment]
有没有办法大神用appium自动化？？

**Comment by xuancang** [comment]
写个adb版本吧，应该是无障碍被检测了

**Comment by czhua1993** [comment]
检测脚本的判断依据是啥，我用apktool改了包名也不行 😂 但是无障碍里面其它的#轻启动#什么的不算脚本。。。

**Comment by div-wang** [comment]
最简单方式就是安装老版本淘宝，亲测9.5.7可用

**Comment by hidetag** [comment]
淘宝检测了无障碍的服务是不是在运行

**Comment by roceys** [comment]
> 最简单方式就是安装老版本淘宝，亲测9.5.7可用

已验证，已适配。
