### ISSUE TITLE
脚本撸的金币好像被限制了

### ISSUE THREAD

**Issue by csdjl88** [roceys/Taobao#15]
任务本来获取的金币应该有1W左右
打开autojs运行脚本获取的金币只有100-200 
不知道大神有无遇到这个情况
关闭autojs后  情况依然估计要过几个小时才能解封

**Comment by yongchao1210** [comment]
是的， 我的貌似也是这个样子 ，今天开始运行第一个任务显示加300几笔，赶紧关掉，然手手工就正常了，，啥情况？

**Comment by csdjl88** [comment]
> 是的， 我的貌似也是这个样子 ，今天开始运行第一个任务显示加300几笔，赶紧关掉，然手手工就正常了，，啥情况？

我的号没有立刻恢复过来，我关机重启过后还是这样，过了一个晚上再看看

**Comment by roceys** [comment]
正常啊！ 你们检查下自己手机应用市场是不是后台自动升级了淘宝app版本为最新。

**Comment by yongchao1210** [comment]
> 正常啊！ 你们检查下自己手机应用市场是不是后台自动升级了淘宝app版本为最新。

还真是的

**Comment by csdjl88** [comment]
> 正常啊！ 你们检查下自己手机应用市场是不是后台自动升级了淘宝app版本为最新。

感觉大神指路，换了低版本就可以了
