### ISSUE TITLE
支付宝的 Bug

### ISSUE THREAD

**Issue by Suremotoo** [roceys/Taobao#16]
偷偷告诉你们，其实支付宝的 Bug，上一年就是有~🙃🙃

**Comment by roceys** [comment]
> 偷偷告诉你们，其实支付宝的 Bug，上一年就是有~🙃🙃

老支付宝用户了😂😂😂

**Comment by Suremotoo** [comment]
> > 偷偷告诉你们，其实支付宝的 Bug，上一年就是有~![](https://cdn.emojidex.com/emoji/xhdpi/upside_down_face.png)![](https://cdn.emojidex.com/emoji/xhdpi/upside_down_face.png)
> 
> 老支付宝用户了![](https://cdn.emojidex.com/emoji/xhdpi/joy.png)![](https://cdn.emojidex.com/emoji/xhdpi/joy.png)![](https://cdn.emojidex.com/emoji/xhdpi/joy.png)

昨天支付宝修复了，我怀疑就是你这个教程暴露的💩💩，上年都没修复，直到我看到你这个之前，还没修复
诺，你要反思反思了

![image](https://user-images.githubusercontent.com/26423989/97379365-9c1ff800-18ff-11eb-87ea-921cafa93440.png)

**Comment by roceys** [comment]
> > > 偷偷告诉你们，其实支付宝的 Bug，上一年就是有~![](https://camo.githubusercontent.com/77df13d5d248d7da55f0dea7f0d1e4f3d72d1138/68747470733a2f2f63646e2e656d6f6a696465782e636f6d2f656d6f6a692f78686470692f7570736964655f646f776e5f666163652e706e67)![](https://camo.githubusercontent.com/77df13d5d248d7da55f0dea7f0d1e4f3d72d1138/68747470733a2f2f63646e2e656d6f6a696465782e636f6d2f656d6f6a692f78686470692f7570736964655f646f776e5f666163652e706e67)
> > 
> > 
> > 老支付宝用户了![](https://camo.githubusercontent.com/71962b581337557c4e721016a89fd228ac0e0dec/68747470733a2f2f63646e2e656d6f6a696465782e636f6d2f656d6f6a692f78686470692f6a6f792e706e67)![](https://camo.githubusercontent.com/71962b581337557c4e721016a89fd228ac0e0dec/68747470733a2f2f63646e2e656d6f6a696465782e636f6d2f656d6f6a692f78686470692f6a6f792e706e67)![](https://camo.githubusercontent.com/71962b581337557c4e721016a89fd228ac0e0dec/68747470733a2f2f63646e2e656d6f6a696465782e636f6d2f656d6f6a692f78686470692f6a6f792e706e67)
> 
> 昨天支付宝修复了，我怀疑就是你这个教程暴露的💩💩，上年都没修复，直到我看到你这个之前，还没修复
> 诺，你要反思反思了
> 
> ![image](https://user-images.githubusercontent.com/26423989/97379365-9c1ff800-18ff-11eb-87ea-921cafa93440.png)

属实如此，我昨天上午还有bug的，今天就没了，看来阿里程序员也经常用脚本。
