### ISSUE TITLE
9.5.7 也变成 1% 喵币了

### ISSUE THREAD

**Issue by oumoe** [roceys/Taobao#22]
逛商城任务全都变成 100 币，点猫掉落还是正常。

**Comment by roceys** [comment]
目前我这边正常哦

**Comment by csdjl88** [comment]
我2个安卓机  一个魅族   一个vivo  
一样的手淘9.5.7  
一样的autojs(4.1.1 Alpha2)版本
魅族没有运行脚本没有出现1%的情况
vivo不管脚本还是手动都出现任务1%的情况

**Comment by roceys** [comment]
2020年10月31日 11:51:58 依然正常收益

**Comment by roceys** [comment]
> 我2个安卓机 一个魅族 一个vivo
> 一样的手淘9.5.7
> 一样的autojs(4.1.1 Alpha2)版本
> 魅族没有运行脚本没有出现1%的情况
> vivo不管脚本还是手动都出现任务1%的情况

你的tb账号风险过高

**Comment by milim6** [comment]
> > 我2个安卓机 一个魅族 一个vivo
> > 一样的手淘9.5.7
> > 一样的autojs(4.1.1 Alpha2)版本
> > 魅族没有运行脚本没有出现1%的情况
> > vivo不管脚本还是手动都出现任务1%的情况
> 
> 你的tb账号风险过高

我也是这样，使用旧版本也会被检测，而且只要被检测了不挂开不开脚本都是1%，但是更新了新版本就可以恢复，但是新版本还是会被检测= =

**Comment by csdjl88** [comment]
> > > 我2个安卓机 一个魅族 一个vivo
> > > 一样的手淘9.5.7
> > > 一样的autojs(4.1.1 Alpha2)版本
> > > 魅族没有运行脚本没有出现1%的情况
> > > vivo不管脚本还是手动都出现任务1%的情况
> > 
> > 
> > 你的tb账号风险过高
> 
> 我也是这样，使用旧版本也会被检测，而且只要被检测了不挂开不开脚本都是1%，但是更新了新版本就可以恢复，但是新版本还是会被检测= =

在另一个脚本那里说是用手淘9.0.0版本才行
经测  还是受到限制
现在把手淘更新到最新版本9.15.0手动做任务
任务奖励正常

**Comment by Coolrui1816** [comment]
更新到最新就正常了？？我换iOS手动 奖励还是1%

**Comment by csdjl88** [comment]
> 更新到最新就正常了？？我换iOS手动 奖励还是1%

实在不行的话  你固定一个手机设备  在那个手机设备上更改密码  然后手淘的安全中心那里 设备管理  把不用的设备全部删掉  这段时间就不要在登录上去了
我是这么操作过的

**Comment by Coolrui1816** [comment]
> > 更新到最新就正常了？？我换iOS手动 奖励还是1%
> 
> 实在不行的话 你固定一个手机设备 在那个手机设备上更改密码 然后手淘的安全中心那里 设备管理 把不用的设备全部删掉 这段时间就不要在登录上去了
> 我是这么操作过的

好的谢谢

**Comment by xionghaizhi** [comment]
我的9.5.7也1%了

**Comment by xionghaizhi** [comment]
tb_9.0.0版本 可以用。但是脚本不能用最新的，不是9.5.7不让用

**Comment by roceys** [comment]
> tb_9.0.0版本 可以用。但是脚本不能用最新的，不是9.5.7不让用

9.0.0也一样，看账号的了

**Comment by xionghaizhi** [comment]
> > tb_9.0.0版本 可以用。但是脚本不能用最新的，不是9.5.7不让用
> 
> 9.0.0也一样，看账号的了

确实是 早上不行了

**Comment by roceys** [comment]
2020年11月1日 21:12:14 正常收益

**Comment by roceys** [comment]
2020年11月4日 21:01:22 正常
